export const WINDOWS_PATH="windows"
export const SETUP_PATH="setup"
export const ERRORI_PATH="errori"
export const HARDWARE_PATH="hardware"
export const CURIOSITA_PATH="curiosita"
export const ALTRO_PATH="altro"